import { createFileRoute } from "@tanstack/react-router";

import { SiteHeader } from "@/components/site/SiteHeader";
import { SiteFooter } from "@/components/site/SiteFooter";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — Job It Ready" },
      {
        name: "description",
        content: "The terms that govern use of Job It Ready's software and subscription.",
      },
    ],
  }),
  component: TermsOfService,
});

function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />

      <section className="mx-auto max-w-3xl px-5 py-14">
        <p className="label-caps text-primary">Legal</p>
        <h1 className="mt-3 text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated September 6, 2026.</p>

        <div className="prose mt-8 max-w-none space-y-6 text-[15px] leading-relaxed text-foreground">
          <p>
            These terms govern your use of Job It Ready's software (the "Service"). By creating an account or
            using the Service, you agree to them. If you're using Job It Ready on behalf of a business, you're
            agreeing on that business's behalf.
          </p>

          <h2 className="text-xl font-semibold">What Job It Ready is</h2>
          <p>Job It Ready lets a service business collect a photo and description from a customer and get an
            AI-generated diagnosis and price estimate back, then manage that lead through to a booked job.
            It's a tool to help price and organize work faster — it doesn't replace a business's own
            judgment, licensing, or professional responsibility for the work it performs.</p>

          <h2 className="text-xl font-semibold">AI-generated estimates</h2>
          <p>Diagnoses and price estimates are generated by an AI model from a photo and description, and
            are estimates only — not a guarantee of the final scope, price, or outcome of any job. The
            business using Job It Ready is responsible for reviewing, adjusting, and standing behind any
            estimate before presenting it to a customer as a quote.</p>

          <h2 className="text-xl font-semibold">Accounts and subscriptions</h2>
          <ul className="list-disc space-y-2 pl-6">
            <li>You need an account to use the dashboard, and you're responsible for keeping your login
              credentials secure.</li>
            <li>Paid plans are billed monthly through Stripe and can be canceled at any time from the
              billing page — no minimum term, no cancellation fee.</li>
            <li>We may suspend or terminate an account for abuse, non-payment, or violation of these terms.</li>
          </ul>

          <h2 className="text-xl font-semibold">Acceptable use</h2>
          <p>Don't use Job It Ready to send unsolicited messages, collect data unlawfully, misrepresent a
            business, or interfere with the Service's operation. WhatsApp messaging in particular is subject
            to WhatsApp's and Twilio's own policies in addition to these terms.</p>

          <h2 className="text-xl font-semibold">Your content</h2>
          <p>You (and your customers, through you) retain ownership of photos, descriptions, and other
            content submitted to Job It Ready. You grant us the license needed to process that content in order
            to provide the Service — including sending it to the third-party providers described in our
            Privacy Policy.</p>

          <h2 className="text-xl font-semibold">Disclaimer and limitation of liability</h2>
          <p>The Service is provided "as is." To the fullest extent permitted by law, Job It Ready isn't liable
            for indirect, incidental, or consequential damages arising from use of the Service, including
            damages related to the accuracy of an AI-generated estimate or diagnosis. Our total liability for
            any claim is limited to the amount you paid us in the 12 months before the claim arose.</p>

          <h2 className="text-xl font-semibold">Changes</h2>
          <p>We may update these terms as the Service changes. Continued use after an update means you
            accept the revised terms.</p>

          <h2 className="text-xl font-semibold">Governing law</h2>
          <p>These terms are governed by the laws of the State of Texas, without regard to conflict-of-law
            rules.</p>

          <h2 className="text-xl font-semibold">Contact</h2>
          <p>Questions about these terms: <a className="text-primary underline-offset-4 hover:underline" href="mailto:legal@frontdesk.tools">legal@frontdesk.tools</a></p>
        </div>
      </section>

      <SiteFooter />
    </div>
  );
}
