/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardLeadsRouteImport } from './routes/dashboard.leads'
import { Route as DashboardPriceSheetRouteImport } from './routes/dashboard.price-sheet'
import { Route as DashboardWidgetRouteImport } from './routes/dashboard.widget'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as QuoteSlugRouteImport } from './routes/quote.$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api.whatsapp.webhook'
import { Route as DashboardLeadsIndexRouteImport } from './routes/dashboard.leads.index'
import { Route as DashboardLeadsIdRouteImport } from './routes/dashboard.leads.$id'
import { Route as DashboardSettingsBillingRouteImport } from './routes/dashboard.settings.billing'
import { Route as DashboardSettingsBusinessRouteImport } from './routes/dashboard.settings.business'
import { Route as DashboardSettingsQualificationsRouteImport } from './routes/dashboard.settings.qualifications'
import { Route as DashboardLeadsIdIndexRouteImport } from './routes/dashboard.leads.$id.index'
import { Route as DashboardLeadsIdInvoiceRouteImport } from './routes/dashboard.leads.$id.invoice'
import { Route as DashboardLeadsIdProposalRouteImport } from './routes/dashboard.leads.$id.proposal'
import { Route as DashboardLeadsIdReceiptRouteImport } from './routes/dashboard.leads.$id.receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeadsRoute = DashboardLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPriceSheetRoute = DashboardPriceSheetRouteImport.update({
  id: '/price-sheet',
  path: '/price-sheet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWidgetRoute = DashboardWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => DashboardRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const QuoteSlugRoute = QuoteSlugRouteImport.update({
  id: '/quote/$slug',
  path: '/quote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLeadsRoute,
} as any)
const DashboardLeadsIdRoute = DashboardLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardLeadsRoute,
} as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsBusinessRoute =
  DashboardSettingsBusinessRouteImport.update({
    id: '/settings/business',
    path: '/settings/business',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsQualificationsRoute =
  DashboardSettingsQualificationsRouteImport.update({
    id: '/settings/qualifications',
    path: '/settings/qualifications',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardLeadsIdIndexRoute = DashboardLeadsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLeadsIdRoute,
} as any)
const DashboardLeadsIdInvoiceRoute = DashboardLeadsIdInvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => DashboardLeadsIdRoute,
} as any)
const DashboardLeadsIdProposalRoute =
  DashboardLeadsIdProposalRouteImport.update({
    id: '/proposal',
    path: '/proposal',
    getParentRoute: () => DashboardLeadsIdRoute,
  } as any)
const DashboardLeadsIdReceiptRoute = DashboardLeadsIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => DashboardLeadsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/price-sheet': typeof DashboardPriceSheetRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/quote/$slug': typeof QuoteSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdRouteWithChildren
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/business': typeof DashboardSettingsBusinessRoute
  '/dashboard/settings/qualifications': typeof DashboardSettingsQualificationsRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/dashboard/leads/$id/invoice': typeof DashboardLeadsIdInvoiceRoute
  '/dashboard/leads/$id/proposal': typeof DashboardLeadsIdProposalRoute
  '/dashboard/leads/$id/receipt': typeof DashboardLeadsIdReceiptRoute
  '/dashboard/leads/$id/': typeof DashboardLeadsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/price-sheet': typeof DashboardPriceSheetRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/quote/$slug': typeof QuoteSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/business': typeof DashboardSettingsBusinessRoute
  '/dashboard/settings/qualifications': typeof DashboardSettingsQualificationsRoute
  '/dashboard/leads': typeof DashboardLeadsIndexRoute
  '/dashboard/leads/$id/invoice': typeof DashboardLeadsIdInvoiceRoute
  '/dashboard/leads/$id/proposal': typeof DashboardLeadsIdProposalRoute
  '/dashboard/leads/$id/receipt': typeof DashboardLeadsIdReceiptRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/get-started': typeof GetStartedRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/leads': typeof DashboardLeadsRouteWithChildren
  '/dashboard/price-sheet': typeof DashboardPriceSheetRoute
  '/dashboard/widget': typeof DashboardWidgetRoute
  '/quote/$slug': typeof QuoteSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/dashboard/leads/$id': typeof DashboardLeadsIdRouteWithChildren
  '/dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/dashboard/settings/business': typeof DashboardSettingsBusinessRoute
  '/dashboard/settings/qualifications': typeof DashboardSettingsQualificationsRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/dashboard/leads/$id/invoice': typeof DashboardLeadsIdInvoiceRoute
  '/dashboard/leads/$id/proposal': typeof DashboardLeadsIdProposalRoute
  '/dashboard/leads/$id/receipt': typeof DashboardLeadsIdReceiptRoute
  '/dashboard/leads/$id/': typeof DashboardLeadsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/leads'
    | '/dashboard/price-sheet'
    | '/dashboard/widget'
    | '/quote/$slug'
    | '/dashboard/'
    | '/onboarding/'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/dashboard/leads/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/business'
    | '/dashboard/settings/qualifications'
    | '/dashboard/leads/'
    | '/dashboard/leads/$id/invoice'
    | '/dashboard/leads/$id/proposal'
    | '/dashboard/leads/$id/receipt'
    | '/dashboard/leads/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/price-sheet'
    | '/dashboard/widget'
    | '/quote/$slug'
    | '/dashboard'
    | '/onboarding'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/business'
    | '/dashboard/settings/qualifications'
    | '/dashboard/leads'
    | '/dashboard/leads/$id/invoice'
    | '/dashboard/leads/$id/proposal'
    | '/dashboard/leads/$id/receipt'
    | '/dashboard/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/get-started'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/dashboard/analytics'
    | '/dashboard/leads'
    | '/dashboard/price-sheet'
    | '/dashboard/widget'
    | '/quote/$slug'
    | '/dashboard/'
    | '/onboarding/'
    | '/api/stripe/webhook'
    | '/api/whatsapp/webhook'
    | '/dashboard/leads/$id'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/business'
    | '/dashboard/settings/qualifications'
    | '/dashboard/leads/'
    | '/dashboard/leads/$id/invoice'
    | '/dashboard/leads/$id/proposal'
    | '/dashboard/leads/$id/receipt'
    | '/dashboard/leads/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  GetStartedRoute: typeof GetStartedRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  QuoteSlugRoute: typeof QuoteSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads': {
      id: '/dashboard/leads'
      path: '/leads'
      fullPath: '/dashboard/leads'
      preLoaderRoute: typeof DashboardLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/price-sheet': {
      id: '/dashboard/price-sheet'
      path: '/price-sheet'
      fullPath: '/dashboard/price-sheet'
      preLoaderRoute: typeof DashboardPriceSheetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/widget': {
      id: '/dashboard/widget'
      path: '/widget'
      fullPath: '/dashboard/widget'
      preLoaderRoute: typeof DashboardWidgetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/quote/$slug': {
      id: '/quote/$slug'
      path: '/quote/$slug'
      fullPath: '/quote/$slug'
      preLoaderRoute: typeof QuoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/': {
      id: '/dashboard/leads/'
      path: '/'
      fullPath: '/dashboard/leads/'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof DashboardLeadsRoute
    }
    '/dashboard/leads/$id': {
      id: '/dashboard/leads/$id'
      path: '/$id'
      fullPath: '/dashboard/leads/$id'
      preLoaderRoute: typeof DashboardLeadsIdRouteImport
      parentRoute: typeof DashboardLeadsRoute
    }
    '/dashboard/settings/billing': {
      id: '/dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/business': {
      id: '/dashboard/settings/business'
      path: '/settings/business'
      fullPath: '/dashboard/settings/business'
      preLoaderRoute: typeof DashboardSettingsBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/qualifications': {
      id: '/dashboard/settings/qualifications'
      path: '/settings/qualifications'
      fullPath: '/dashboard/settings/qualifications'
      preLoaderRoute: typeof DashboardSettingsQualificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leads/$id/': {
      id: '/dashboard/leads/$id/'
      path: '/'
      fullPath: '/dashboard/leads/$id/'
      preLoaderRoute: typeof DashboardLeadsIdIndexRouteImport
      parentRoute: typeof DashboardLeadsIdRoute
    }
    '/dashboard/leads/$id/invoice': {
      id: '/dashboard/leads/$id/invoice'
      path: '/invoice'
      fullPath: '/dashboard/leads/$id/invoice'
      preLoaderRoute: typeof DashboardLeadsIdInvoiceRouteImport
      parentRoute: typeof DashboardLeadsIdRoute
    }
    '/dashboard/leads/$id/proposal': {
      id: '/dashboard/leads/$id/proposal'
      path: '/proposal'
      fullPath: '/dashboard/leads/$id/proposal'
      preLoaderRoute: typeof DashboardLeadsIdProposalRouteImport
      parentRoute: typeof DashboardLeadsIdRoute
    }
    '/dashboard/leads/$id/receipt': {
      id: '/dashboard/leads/$id/receipt'
      path: '/receipt'
      fullPath: '/dashboard/leads/$id/receipt'
      preLoaderRoute: typeof DashboardLeadsIdReceiptRouteImport
      parentRoute: typeof DashboardLeadsIdRoute
    }
  }
}

interface DashboardLeadsIdRouteChildren {
  DashboardLeadsIdInvoiceRoute: typeof DashboardLeadsIdInvoiceRoute
  DashboardLeadsIdProposalRoute: typeof DashboardLeadsIdProposalRoute
  DashboardLeadsIdReceiptRoute: typeof DashboardLeadsIdReceiptRoute
  DashboardLeadsIdIndexRoute: typeof DashboardLeadsIdIndexRoute
}

const DashboardLeadsIdRouteChildren: DashboardLeadsIdRouteChildren = {
  DashboardLeadsIdInvoiceRoute: DashboardLeadsIdInvoiceRoute,
  DashboardLeadsIdProposalRoute: DashboardLeadsIdProposalRoute,
  DashboardLeadsIdReceiptRoute: DashboardLeadsIdReceiptRoute,
  DashboardLeadsIdIndexRoute: DashboardLeadsIdIndexRoute,
}

const DashboardLeadsIdRouteWithChildren =
  DashboardLeadsIdRoute._addFileChildren(DashboardLeadsIdRouteChildren)

interface DashboardLeadsRouteChildren {
  DashboardLeadsIdRoute: typeof DashboardLeadsIdRouteWithChildren
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
}

const DashboardLeadsRouteChildren: DashboardLeadsRouteChildren = {
  DashboardLeadsIdRoute: DashboardLeadsIdRouteWithChildren,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
}

const DashboardLeadsRouteWithChildren = DashboardLeadsRoute._addFileChildren(
  DashboardLeadsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardLeadsRoute: typeof DashboardLeadsRouteWithChildren
  DashboardPriceSheetRoute: typeof DashboardPriceSheetRoute
  DashboardWidgetRoute: typeof DashboardWidgetRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsBusinessRoute: typeof DashboardSettingsBusinessRoute
  DashboardSettingsQualificationsRoute: typeof DashboardSettingsQualificationsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardLeadsRoute: DashboardLeadsRouteWithChildren,
  DashboardPriceSheetRoute: DashboardPriceSheetRoute,
  DashboardWidgetRoute: DashboardWidgetRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsBusinessRoute: DashboardSettingsBusinessRoute,
  DashboardSettingsQualificationsRoute: DashboardSettingsQualificationsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  GetStartedRoute: GetStartedRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  QuoteSlugRoute: QuoteSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
